#!/usr/bin/env bash
# BWTKT Core Functions
# Bitwarden CLI session management and SSH auto-login integration
# Provides robust session handling and SSH aliases with credential automation
#
# This file should not contain user-specific configuration.
# User configuration is handled by the user's init script generated by setup.sh

# Get the directory where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# Set up SSH and SCP aliases to use the auto-login wrapper
alias ssh=". ${SCRIPT_DIR}/bitwarden-ssh-auto-login/bwssh ssh"
alias scp=". ${SCRIPT_DIR}/bitwarden-ssh-auto-login/bwssh scp"

# Check that BW_USER is set (should be set by user's init script)
if [[ -z "${BW_USER:-}" ]]; then
    echo "Warning: BW_USER not set. Please run the BWTKT setup script."
    echo "Or manually set: export BW_USER='your-bitwarden-email'"
fi

bw() {
  bw_exec=$(sh -c "which bw")
  local -r bw_session_file='/var/root/.bitwarden.session' # Only accessible as root
  local -r bw_session_dir=$(dirname "$bw_session_file")
  
  # Make bw_session global so it persists between function calls
  # Don't declare it as local

  # Check if the session directory exists
  _check_session_directory() {
    if [ ! -d "$bw_session_dir" ]; then
      echo "Warning: Session directory '$bw_session_dir' does not exist."
      read -p "Would you like to create it? (y/N): " -n 1 -r
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        if sudo mkdir -p "$bw_session_dir"; then
          echo "Successfully created directory: $bw_session_dir"
        else
          echo "Error: Failed to create directory: $bw_session_dir"
          return 1
        fi
      else
        echo "Cannot proceed without the session directory."
        return 1
      fi
    fi
  }

  _read_token_from_file() {
    local -r err_token_not_found="Token not found, please run bw --regenerate-session-key"
    case $1 in
    '--force')
      unset bw_session
      ;;
    esac

    if [ "$bw_session" = "$err_token_not_found" ]; then
      unset bw_session
    fi

    # If the session key env variable is not set, read it from the file
    if [ -z "$bw_session" ]; then
      # Check if session file exists and read it in one sudo call
      if [ ! -f "$bw_session_file" ]; then
        return 1  # No session file, let caller handle this
      fi
      
      # Try to read the session file
      bw_session="$(sudo cat $bw_session_file 2>/dev/null)"
      local read_exit_code=$?
      
      if [ "$read_exit_code" -ne "0" ] || [ -z "$bw_session" ]; then
        sudo -k # Clear cache only on read error
        return 1  # Couldn't read session, let caller handle this
      fi
    fi
    
    return 0  # Success
  }

  case $1 in
  '--regenerate-session-key')
    echo "Regenerating session key, this has invalidated all existing sessions..."
    
    # Check if session directory exists before trying to create the session file
    _check_session_directory || return 1
    
    sudo rm -f /var/root/.bitwarden.session && ${bw_exec} logout 2>/dev/null # Invalidate all existing sessions

    ${bw_exec} login "${BW_USER}" --raw | sudo tee /var/root/.bitwarden.session &>/dev/null # Generate new session key

    _read_token_from_file --force # Read the new session key for immediate use
    sudo -k                       # De-elevate privileges, only doing this now so _read_token_from_file can resuse the same sudo session
    ;;

  'login' | 'logout' | 'config')
    ${bw_exec} "$@"
    ;;

  '--help' | '-h' | '')
    ${bw_exec} "$@"
    echo "To regenerate your session key type:"
    echo "  bw --regenerate-session-key"
    ;;    *)
    _read_token_from_file

    # If _read_token_from_file failed, we need to regenerate session and retry
    if [ $? -ne 0 ]; then
      echo "No valid session found. Regenerating session..."
      
      # Regenerate session first
      if bw --regenerate-session-key; then
        echo "Session regenerated successfully. Retrying command..."
        # Now retry the original command
        _read_token_from_file --force
        ${bw_exec} "$@" --session "$bw_session"
      else
        echo "Failed to regenerate session."
        sudo -k  # Clear cache on error
        return 1
      fi
    else
      # We have a valid session, run the command
      ${bw_exec} "$@" --session "$bw_session"
    fi
    
    # Don't clear sudo cache after successful operations - let it persist for subsequent calls
    ;;
  esac
}
