#!/usr/bin/env bash
# BWTKT Core Functions
# Bitwarden CLI session management and SSH auto-login integration
# Provides robust session handling and SSH aliases with credential automation
#
# This file should not contain user-specific configuration.
# User configuration is handled by the user's init script generated by setup.sh

# Get the directory where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# Shared terminal UI helpers (ui_info/ui_ok/ui_warn/ui_err/ui_confirm)
source "${SCRIPT_DIR}/bwtkt-ui.sh"

# Set up SSH and SCP aliases to use the auto-login wrapper
alias ssh=". ${SCRIPT_DIR}/bitwarden-ssh-auto-login/bwssh /usr/bin/ssh"
alias scp=". ${SCRIPT_DIR}/bitwarden-ssh-auto-login/bwssh /usr/bin/scp"

# Expose binit (Bitwarden-backed kinit) and the bwtkt CLI on PATH
for _bwtkt_dir in "${SCRIPT_DIR}/bitwarden-kinit-auto-login" "${SCRIPT_DIR}/bin"; do
    case ":$PATH:" in
        *":${_bwtkt_dir}:"*) ;;
        *) export PATH="${_bwtkt_dir}:$PATH" ;;
    esac
done
unset _bwtkt_dir

# Check that BW_USER is set (should be set by user's init script)
if [[ -z "${BW_USER:-}" ]]; then
    ui_warn "BW_USER not set — run the BWTKT setup script or: export BW_USER='your-bitwarden-email'"
fi

bw() {
  bw_exec=$(sh -c "which bw")
  local -r bw_session_file='/var/root/.bitwarden.session' # Only accessible as root
  local -r bw_session_dir=$(dirname "$bw_session_file")
  
  # Make bw_session global so it persists between function calls
  # Don't declare it as local

  # Check if the session directory exists
  _check_session_directory() {
    if [ ! -d "$bw_session_dir" ]; then
      echo "Warning: Session directory '$bw_session_dir' does not exist."
      read -p "Would you like to create it? (y/N): " -n 1 -r
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        if sudo mkdir -p "$bw_session_dir"; then
          echo "Successfully created directory: $bw_session_dir"
        else
          echo "Error: Failed to create directory: $bw_session_dir"
          return 1
        fi
      else
        echo "Cannot proceed without the session directory."
        return 1
      fi
    fi
  }

  _read_token_from_file() {
    local -r err_token_not_found="Token not found, please run bw --regenerate-session-key"
    case $1 in
    '--force')
      unset bw_session
      ;;
    esac

    if [ "$bw_session" = "$err_token_not_found" ]; then
      unset bw_session
    fi

    # If the session key env variable is not set, read it from the file
    if [ -z "$bw_session" ]; then
      # Check if session file exists and read it in one sudo call
      if [ ! -f "$bw_session_file" ]; then
        return 1  # No session file, let caller handle this
      fi
      
      # Try to read the session file
      bw_session="$(sudo cat $bw_session_file 2>/dev/null)"
      local read_exit_code=$?
      # Drop the cached sudo timestamp immediately: otherwise any process
      # running as this user could silently re-read the session key for the
      # duration of the sudo cache window (~15 min by default)
      sudo -k

      if [ "$read_exit_code" -ne "0" ] || [ -z "$bw_session" ]; then
        return 1  # Couldn't read session, let caller handle this
      fi
    fi
    
    return 0  # Success
  }

  case $1 in
  'relogin' | '--regenerate-session-key')
    ui_info "regenerating session key — this invalidates all existing sessions"
    
    # Check if session directory exists before trying to create the session file
    _check_session_directory || return 1
    
    sudo rm -f /var/root/.bitwarden.session && ${bw_exec} logout 2>/dev/null # Invalidate all existing sessions

    # Pre-create the session file root-only: sudo tee would create it 0644,
    # leaving the key world-readable until a later chmod
    sudo install -m 600 -o root /dev/null "$bw_session_file"
    ${bw_exec} login "${BW_USER}" --raw | sudo tee "$bw_session_file" &>/dev/null # Generate new session key

    _read_token_from_file --force # Read the new session key for immediate use
    sudo -k                       # De-elevate privileges, only doing this now so _read_token_from_file can resuse the same sudo session
    ;;

  '--prime-session')
    # Read the session key into this shell's memory (one sudo prompt,
    # timestamp dropped immediately). Callers that fetch credentials in
    # command substitutions should prime first: subshells inherit the key,
    # so multiple fetches cost no further prompts.
    _read_token_from_file
    ;;

  'login' | 'logout' | 'config')
    ${bw_exec} "$@"
    ;;

  '--help' | '-h' | '')
    ${bw_exec} "$@"
    ui_info "to renew the bwtkt session key: bw relogin"
    ;;

  *)
    _read_token_from_file

    # If _read_token_from_file failed, we need to regenerate session and retry
    if [ $? -ne 0 ]; then
      ui_warn "no valid Bitwarden session — logging in"

      # Regenerate session first
      if bw relogin; then
        # Now retry the original command
        _read_token_from_file --force
        # Pass the session via the environment, not --session: argv is
        # world-readable in /proc/*/cmdline, the environment is not
        BW_SESSION="$bw_session" ${bw_exec} "$@"
      else
        ui_err "Bitwarden login failed"
        sudo -k  # Clear cache on error
        return 1
      fi
    else
      # We have a valid session, run the command
      BW_SESSION="$bw_session" ${bw_exec} "$@"
    fi
    ;;
  esac
}
